#!/bin/sh

alias ls="ls --color=auto --group-directories-first"
alias ll="ls -alF"
alias grep="grep --color=auto"
alias df="df -h"

alias v="nvim"
alias vo='fzf | { read -r f && nvim "$f"; }'
alias lg="lazygit"

