#!/bin/sh

alias c="clear"
alias ls="ls --color=auto --group-directories-first"
alias ll="ls -alFh"
alias grep="grep --color=auto"
alias df="df -h"

# Vim
alias v="nvim"
alias vo="fzf --preview='bat --color=always {}' -m | xargs -r $EDITOR"
alias voc="(fd -HL '' -E .git --ignore-file $HOME/dotfiles/.gitignore $XDG_CONFIG_HOME && echo $HOME/.zprofile) | vo"

# Lazy
alias lg="lazygit"
alias ld="lazydocker"

alias lr="tree -aI '.git' --gitignore"
