#!/bin/sh

export PATH="$PATH:/home/kstroz/.local/bin"

# fnm
eval "$(fnm env --use-on-cd)"

# pnpm
export PNPM_HOME="$XDG_DATA_HOME/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
