#!/bin/sh

export PATH="$PATH:/home/kstroz/.local/bin"

case "$(uname -s)" in
  Linux)
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  ;;
  Darwin)
  ;;
esac

export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_ENV_HINTS=1
export HOMEBREW_BUNDLE_FILE="$XDG_CONFIG_HOME/brew/.Brewfile"

export MANPAGER="nvim +Man!"

# bat
export BAT_THEME="gruvbox-dark"

# fzf
source <(fzf --zsh)
export FZF_DEFAULT_OPTS="--style minimal --layout=reverse --border=bold --margin=4% --preview='bat --color=always {}'"

# fnm
eval "$(fnm env --use-on-cd)"

# pnpm
export PNPM_HOME="$XDG_DATA_HOME/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
