#!/bin/sh

######################################################################
# Aliases
######################################################################

alias confzsh="$EDITOR $HOME/.zshrc"
alias confgit="$EDITOR $HOME/.gitconfig"
