#!/bin/sh

export PATH="$PATH:/home/kstroz/.local/bin"

case "$(uname -s)" in
  Linux)
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  ;;
  Darwin)
  ;;
esac

export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_ENV_HINTS=1
export HOMEBREW_BUNDLE_FILE="$XDG_CONFIG_HOME/brew/.Brewfile"

export MANPAGER="nvim +Man!"
export PYENV_ROOT="$XDG_DATA_HOME/pyenv"

# bat
export BAT_THEME="gruvbox-dark"

# fzf
source <(fzf --zsh)
export FZF_DEFAULT_OPTS="\
  --style minimal \
  --layout=reverse \
  --border=bold \
  --margin=4% \
  --color=border:#a89984 \
  --color=fg:#ebdbb2 \
  --color=fg+:#ebdbb2 \
  --color=bg+:#32302f \
  --color=info:#928374 \
  --color=hl:#fe8019 \
  --color=hl+:#fe8019 \
  --color=pointer:#fb4934 \
  --color=marker:#d3869b \
  --color=gutter:#a89984 \
  --color=prompt:#b8bb26 \
  --preview='bat --color=always {}'\
"

# fnm
eval "$(fnm env --use-on-cd)"

# pnpm
export PNPM_HOME="$XDG_DATA_HOME/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
