#!/bin/sh

function zsh_add_plugin() {
  local REPO="$1"
  local PLUGIN="$(basename "$REPO")"
  local PLUGIN_DIR="$XDG_CONFIG_HOME/zsh/plugins/$PLUGIN"

  if [[ ! -d "$PLUGIN_DIR" ]]; then
    git clone --depth=1 "https://github.com/$REPO.git" "$PLUGIN_DIR"
    echo
  fi

  for FILE in \
    "$PLUGIN_DIR/$PLUGIN.plugin.zsh" \
    "$PLUGIN_DIR/$PLUGIN.zsh" \
    "$PLUGIN_DIR/$PLUGIN.zsh-theme"
  do
    [[ -f "$FILE" ]] && source "$FILE" && return
  done
}
